
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/contador_rfwild 

module contador_rfwild(clk, reset, contador);
  input clk, reset;
  output [3:0] contador;
  wire clk, reset;
  wire [3:0] contador;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10;
  DFFR_E \contador_reg[3] (.RN (reset), .CLK (clk), .D (n_10), .Q
       (contador[3]), .QBAR (UNCONNECTED));
  XNOR2_C g65(.A (contador[3]), .B (n_8), .Z (n_10));
  DFFR_E \contador_reg[2] (.RN (reset), .CLK (clk), .D (n_9), .Q
       (contador[2]), .QBAR (UNCONNECTED0));
  XNOR2_C g67(.A (contador[2]), .B (n_6), .Z (n_9));
  NAND2_D g68(.A (n_7), .B (contador[2]), .Z (n_8));
  DFFR_E \contador_reg[1] (.RN (reset), .CLK (clk), .D (n_5), .Q
       (contador[1]), .QBAR (UNCONNECTED1));
  INVERT_H g71(.A (n_6), .Z (n_7));
  XOR2_C g69(.A (contador[1]), .B (contador[0]), .Z (n_5));
  DFFR_E \contador_reg[0] (.RN (reset), .CLK (clk), .D (n_4), .Q
       (contador[0]), .QBAR (n_4));
  NAND2_D g72(.A (contador[0]), .B (contador[1]), .Z (n_6));
endmodule

